apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: college
  name: college
  labels:
    app: college-web
spec:
  selector:
    matchLabels:
      app: college-web
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: college-web
    spec:
      containers:
      - name: college
        image: yogeshchaudhary/college
        ports:
        - containerPort: 80
