apiVersion: v1
kind: ReplicationController
metadata:
  name: college
spec:
  replicas: 3
  selector:
    app: college
  template:
    metadata:
      name: college
      labels:
        app: college 
    spec:
      containers:
      - name: college
        image: yogeshchaudhary/college
        ports:
        - containerPort: 80
