apiVersion: v1
kind: Service
metadata:
  namespace: college
  name: my-service
  labels:
    app: college-web
spec:
  type: NodePort
  selector:
    app: college-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
