apiVersion: v1
kind: Service
metadata:
  namespace: college
  name: my-service
spec:
  selector:
    app: college-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
